config_name: wan-bidir-lora-no-gan-256
load_checkpoint_config_name: wan-bidir-lora-no-gan-256

independent_first_frame: false
warp_denoising_step: false
same_step_across_blocks: true
last_step_only: false

trainer: lora_diffusion

seed: 0
mixed_precision: true
autocast_dtype: bf16
max_iters: 30000
log_interval: 10
ckpt_interval: 300
max_grad_norm: 1.0
auto_resume: true
allow_checkpoint_config_mismatch: true
wandb_key: 998657fa4d2f50cc5d5cd33330f94255137a1221
wandb_entity: ashish397-university-of-exeter
wandb_project: frodobots_wm
wandb_group: bidirectional-lora
wandb_tags:
  - bidirectional
  - no-gan
max_checkpoints: 100

# LoRA adapter settings
adapter:
  type: lora
  rank: 256
  alpha: 256
  dropout: 0.0
  dtype: bfloat16
  verbose: true

# Optimizer
lr: 5.0e-05
beta1: 0.9
beta2: 0.999
weight_decay: 0.01
batch_size: 1
gradient_accumulation_steps: 1

sequential_sampling: false

# Paths (override as needed)
real_latent_root: /projects/u5as/frodobots_encoded/train
caption_root: /projects/u5as/frodobots_captions/train
val_real_latent_root: /projects/u5as/frodobots_encoded/test
val_caption_root: /projects/u5as/frodobots_captions/test

text_pre_encoded: true

num_training_frames: 21
val_batch_size: 1
val_batches: 64
eval_interval: 50

# Model settings
model_name: Wan2.1-T2V-1.3B
denoising_loss_type: flow  # Flow matching (as used in repo)
num_train_timestep: 1000
gradient_checkpointing: true
num_workers: 24

# GAN loss (latent PatchGAN) settings
enable_gan_loss: false

model_kwargs:
  timestep_shift: 5.0
  local_attn_size: -1
  sink_size: 0

# Logging
logdir: /scratch/u5as/as1748.u5as/frodobots/lora_runs/bidirectional_no_gan

denoising_step_list:
- 1000
- 750
- 500
- 250
ts_schedule: false
