config_name: wan-bidir-lora-inference

# Model + LoRA settings
text_pre_encoded: true
mixed_precision: true
num_train_timestep: 1000
model_name: Wan2.1-T2V-1.3B
model_kwargs:
  timestep_shift: 5.0
  local_attn_size: -1
  sink_size: 0

adapter:
  type: lora
  rank: 128
  alpha: 128
  dropout: 0.0
  dtype: bfloat16
  verbose: false

# Sampling configuration
sampling_steps: 50
sampling_shift: 5.0
sampling_solver: unipc
guidance_scale: 0.0
negative_prompt: ""

# Output
num_output_frames: 21
fps: 16
